* BlogHugo

![[https://github.com/euvaz/bloghugo/actions/workflows/on-merge.yaml/badge.svg][GitHub Workflow Status]]

BlogHugo is my automated blog website powered by [[https://gohugo.io/][Hugo]], a popular static site generator. This repository provides a robust setup for building and deploying a Hugo-based blog using GitHub Actions and a custom Dockerfile, thereby utilizing [[https://www.weave.works/blog/what-is-gitops-really][GitOps]] methodologies. It streamlines the process of managing my blog, automating the build and test process, and ensuring my content stays up-to-date.

** Overview

- [[#-features][Features]]
- [[#-local-testing][Local Testing]]
- [[#-dockerfile][Dockerfile]]
- [[#-license][License]]
- [[#-acknowledgments][Acknowledgments]]

** ⭐ Features

- *Automatic Builds:* With GitHub Actions, every push or pull request triggers an automated build process, ensuring the website is always current and bug-free.
- *Dockerfile:* The Dockerfile included in this repository utilizes [[https://www.nginx.com/][Nginx]] to serve the Hugo web content for easy deployment.

** 🔍 Local Testing

Testing can be performed locally with the Hugo development server:

#+BEGIN_SRC shell
$ hugo server
#+END_SRC

** 🐋 Dockerfile

A Dockerfile is provided for convenience, and can be easily built and deployed:

#+BEGIN_SRC shell
$ docker buildx build --platform linux/amd64 -t bloghugo .
$ docker run -p 8080:80 bloghugo:latest
#+END_SRC

** 🔏 License

See [[./LICENSE][LICENSE]]

** 🤝 Acknowledgments

- [[https://github.com/features/actions][Hugo]] - The world's fastest framework for building websites.
- [[https://github.com/features/actions][GitHub Actions]] - Automate your workflow from idea to production.
- [[https://www.docker.com/][Docker]] - Accelerate how you build, share, and run applications.
