---
name: Docker image
description: Creates a Docker image

inputs:
  token:
    description: GitHub token
    required: true
  push:
    description: Push Images to GHCR
    required: false
    default: "true"
  latest:
    description: Update latest tag
    required: false
    default: "true"

runs:
  using: composite

  steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c # v5
      with:
        images: ghcr.io/${{ github.repository }}
        flavor: |
          latest=${{ fromJSON(inputs.latest) }}
          prefix=v
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Build Docker Image
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ fromJSON(inputs.push) }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          VERSION=${{ steps.meta.outputs.version }}
          BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
          REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}