---
name: Versioned Release

on:
  push:
    tags:
      - v*

jobs:
  release-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3b9b8c884f6b4bb4d5be2779c26374abadae0871

      - name: Build
        uses: ./.github/actions/docker-image
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"